// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"-View all":                             203,
	"0 BTC":                                 136,
	"1.) Go to Edit Profile.":               159,
	"1.) Go to your Notification Settings.": 164,
	"1.) Remove Olmax messages from your spam list":                                                                  171,
	"2.) Add nemo@olmax.com, halfwit@olmax.com, and services@olmax.com to your personal email address book":          172,
	"2.) Look for the \"Email Settings\" field. Make sure you have chosen the email types you want to receive.":      165,
	"2.) Look for the Email Address field. Make sure your address is correct.":                                       160,
	"3.) After adding or removing checkmarks from the right boxes, scroll to the bottom of the page and click Save.": 166,
	"3.) If it is incorrect, add the correct address and click Save.":                                                161,
	"Access to Physicians from around the world":                                                                     107,
	"Acute Pain Medicine": 48,
	"All Olmax physicians must: submit a profile photo, medical diplomas, residency certification or equivalent, verify their phone, email, government ID, and background checks. Patients and physicians can each publish reviews after visit conclusions keeping everyone accountable and respectful.": 229,
	"All payments will be done via ":                       204,
	"Anesthesiology":                                       49,
	"Anonymity":                                            105,
	"Any changes in vision?":                               20,
	"Any fevers or Chills?":                                18,
	"Any heart problems?":                                  22,
	"Any intestinal problems?":                             23,
	"Any kidney problems?":                                 24,
	"Any lung issues?":                                     21,
	"Any nervous system problmes? <i>Strokes</i>":          26,
	"Any problems with muscles or bones?":                  25,
	"Any psychiatric problems? <i>Depression, anxiety</i>": 27,
	"Any weight gain or weight loss?":                      19,
	"Appointment Dates:":                                   94,
	"Appointment Requests":                                 149,
	"Appointment Times":                                    97,
	"Appointments":                                         37,
	"Available patients":                                   44,
	"Bariatric Surgery":                                    50,
	"Become A Partner":                                     41,
	"Become A Provider":                                    211,
	"Bitcoin must be paid in full upon deployment or acceptance of contract.": 183,
	"Can I pay with any currency?":                                            184,
	"Cardiology":                                                              51,
	"Check your email notification settings":                                  162,
	"Check your spam and other email filters":                                 169,
	"Chiropractics":                                                           52,
	"Chronic Pain":                                                            53,
	"Communicate with patients via 3rd party applications, or personal telephone.": 224,
	"Contacting A Physician":     200,
	"Contacting Physician":       178,
	"Copyright 2017, 2018, 2019": 42,
	"Country":                    91,
	"Create Patient Profile":     6,
	"Create your profile":        221,
	"Critical Care":              54,
	"Depending on your provider, emails can take up to a few hours to be delivered. If undelivered or delayed emails continue to be an issue, check with your provider to see if there are any configuration issues or problems with their network that might be affecting your account.": 174,
	"Deposit Funds": 138,
	"Dermatology":   55,
	"Do I need to pay before scheduling an appointment?":             180,
	"Does your pain travel or radiate to another part of your body?": 16,
	"Ear Nose and Throat":          58,
	"Email:":                       115,
	"Emergency Medicine":           56,
	"End Time:":                    99,
	"Endocrinology":                57,
	"Enter Email":                  122,
	"Enter a valid email":          131,
	"Enter password (8+ chars)":    132,
	"Enter your first name":        128,
	"Enter your last name":         129,
	"FAQ":                          31,
	"Family Medicine":              59,
	"Female":                       29,
	"Find a Doctor":                93,
	"Find out what you could earn": 212,
	"First Name:":                  127,
	"First name must be at least 2 characters": 145,
	"First name required":                      144,
	"Forgot your password?":                    117,
	"From:":                                    95,
	"Full name must be at least 2 characters":  88,
	"Full name required":                       87,
	"Gastrointestinology":                      60,
	"Get Paid":                                 225,
	"Get Started":                              213,
	"Have you taken any medications for these symptoms and how much have they worked?": 17,
	"Head and Neck":           61,
	"Hello ":                  4,
	"Help":                    32,
	"Hematology and Oncology": 62,
	"Hepatology":              63,
	"How can I add another appointment or business address to my receipt?": 194,
	"How can we help?":                                                                   188,
	"How do I edit or remove a payment method?":                                          191,
	"How do I make an appointment on Olmax?":                                             202,
	"How do I use Bitcoin to pay?":                                                       193,
	"How do I verify my phone number?":                                                   195,
	"How is the price determined for my appointment?":                                    199,
	"How long have these symptoms lasted?":                                               13,
	"How to become an Olmax Provider":                                                    220,
	"How would you characterize your symptoms? <i>Sharp, Dull, Ache, twisting, ets.</i>": 14,
	"Hyperbaric": 64,
	"I am a patient. How do I check the status of my appointment?": 150,
	"I did not recieve an email confirming nor denying my request": 156,
	"If you do not recieve a confimation email by 12 hrs, then a full refund will be returned to your bitcoin account along with an email stating that an appointment could not be made":                153,
	"If you have other filters or routing rules in your email account that may have sorted Olmax emails elsewhere, be sure to check those, too.</br>Check for issues with your email service provider.": 173,
	"If you have submitted payment, and do not see appointment scheduled on this page; please refer to the %s section.":                                                                                 2,
	"If you recieve an email confirming a cancelation of decline, bitcoin will be returned to your account infull, then you may seek another appointment":                                               155,
	"If your country blocks Olmax Medical?": 175,
	"Immunology":                            65,
	"Infectious Diseases":                   66,
	"Internal Medicine":                     67,
	"Invalid email":                         86,
	"Invalid selection for %s":              47,
	"Invalid selection for question %d":     84,
	"It's free and easy to create a profile on Olmax. Describe your resume, how many patients you can accomodate, set your own times, and add photos and details about yourself.": 222,
	"It's possible your email provider mistakenly sent our messages to your spam or junk folder. To avoid this:":                                                                  170,
	"Last Name:": 130,
	"Last name must be at least 2 characters": 147,
	"Last name required":                      146,
	"Legal":                                   38,
	"Login":                                   118,
	"Make sure your email address is correct": 157,
	"Male":                              28,
	"NO FUNDS CURRENTLY HELD IN ESCROW": 137,
	"Neonatology":                       68,
	"Nephrology":                        69,
	"Neurology":                         70,
	"Neurosurgery":                      71,
	"No":                                209,
	"No matter what your specialty, Olmax makes it simple and secure to reach millions of patients looking for doctors with unique skills and specialties, just like yours.": 215,
	"No selection for %s":          46,
	"No selection for question %d": 83,
	"No.":                          185,
	"Obstetrics and Gynecology":    72,
	"Occupational Medicine":        73,
	"Olmax Medical":                90,
	"Olmax Medical is a world wide network of physicians and patients that enables them to communicate, meet virtually, and negotiate payment on a peer to peer basis, without the interference of insurance giants. We provide a platform where the economics of <i>laissez-fairedes</i> (free-trade) will allow both physicians and patients to negotiate fee for service. Our website provide a platform where both patients and doctors form around the world can deploy customized contracts describing, in detail, the terms of health care. The cost, time, and duration of virtual clinic visits will be pre-determined on contracts posted on our website. The contracts are written by either doctor or patient. Contracts can be created, bought, and sold by anyone, because we believe health care should be available to everyone. It will be our work to investigate and verify physician status. Once doctors are verified, patients will have the opportunity to rate physician performance and bedside manners.": 102,
	"Olmax Medical | Appointments":      0,
	"Olmax Medical | Become A Provider": 210,
	"Olmax Medical | Bookings":          43,
	"Olmax Medical | Create Profile":    5,
	"Olmax Medical | FAQ":               148,
	"Olmax Medical | Find Patients":     45,
	"Olmax Medical | Help":              187,
	"Olmax Medical | Login":             113,
	"Olmax Medical | Messages":          119,
	"Olmax Medical | Our Doctors":       177,
	"Olmax Medical | Profile":           3,
	"Olmax Medical | Sign Up":           125,
	"Olmax Medical | Wallet":            134,
	"Olmax Medical | Welcome":           89,
	"Olmax is built on trust":           228,
	"Olmax offers tools, service tips, 24/7 support, and an on-line community of experienced physicians for questions and sharing ideas for success.":                                                                                                                                          219,
	"Olmax's secure payment system means you will never see a patient without compensation, or have to deal with money directly. Patienst are charged before appointments, and you are paid after the visit is completed. We embrace the future, therefore payments will be via Bitcoin only.": 226,
	"Once an appointment request is submitted, the physician has 4 to 12 hrs to replay. Depending on the urgency. If you would like a reply within 4 hr for urgent consults, an extra fee can be payed. Otherwise doctors have 12 hrs to reply to appointment request.":                        151,
	"Once you have submitted a phone number, you can either receive a text message or call with a confirmation number.":                                                                                                                                                                        232,
	"Opthamology":                            74,
	"Orthopedic Surgery":                     75,
	"Palliative Care":                        76,
	"Password must be at least 8 characters": 142,
	"Password required":                      141,
	"Password:":                              116,
	"Patients will be encouraged to use anonymous names. Medical records are kept between patients and physicians, they are not stored on our servers.": 106,
	"Payment":         109,
	"Payment Methods": 34,
	"Payments will be made with Bitcoin. Minimal fees will be charged by our website for holding the cryptocurrency until clinical visits are complete.": 110,
	"Pediatrics": 77,
	"Physicians from around the world will be able to join our network, see patients from anywhere at anytime.": 108,
	"Please check any of the following if you have experienced in the last 6 weeks:":                            30,
	"Please click the following link to finalize your account creation ":                                        238,
	"Please click the following link to reset your password ":                                                   236,
	"Please give a brief statement regarding the main reason you would like to see your doctor:":                10,
	"Please refer to the following help page: ":                                                                 234,
	"Please submit some information regarding your consult.":                                                    7,
	"Podiatry":                      78,
	"Previous messages: Click here": 121,
	"Prices & Fees":                 198,
	"Prices and Fees":               35,
	"Prices and fees are for the most part determined by doctors and patients.": 207,
	"Prices are set by who deploys the contract (doctor or patient). Fees are structured in a amount of bitcoin (BTC) per unit. In which a unit of time equals 15 mins. All new consults must be a minimum of 2 units, and repeat visits can be 1 unit.": 208,
	"Privacy Policy": 39,
	"Profile information such as government ID, diplomas, phone numbers, and emails will will be verified before being posted on Olmax Medical website.": 231,
	"Pulmonology":            79,
	"Quality Healthcare":     33,
	"Radiaton Oncology":      81,
	"Radiology":              80,
	"Re-enter same password": 143,
	"Reset":                  124,
	"Safety on Olmax":        227,
	"Search":                 100,
	"Search all messages in your email inbox": 167,
	"Second Opinions":                         103,
	"See More":                                111,
	"Send only Bitcoin (BTC) to this address": 139,
	"Sending any other digital asset, including Bitcoin Cash (BCH), will result in permanent loss.": 140,
	"Should I clear my schedule if I have no heard back from my doctor?":                            152,
	"Should I clear my schedule if I have not heard back from the doctor?":                          190,
	"Sign Up":          133,
	"Sign Up for free": 126,
	"Since the time of Hippocrates, patients and doctors were limited to serving and receiving care from physician in their more local community. With our platform patients will not be tied to HMOs or managed health care. In other words, insurance companies or government decisions will no longer chain patients to the type and quality of health care they receive. Doctors with extremely rare specialties will be able to serve communities thousands of miles away from them, and from the comfort of their home if they so desire": 104,
	"Sometimes emails can get lost in your inbox. In your email account, search for terms like \"Olmax Medical\", \"Appointment\", \"Verification\", or other words related to the email you're looking for.": 168,
	"Specialty":             92,
	"Start Time:":           98,
	"Start seeing patients": 230,
	"Subject: Olmax Medical - Reset Your Password\n\n":     235,
	"Subject: Olmax Medical - Verify your new account\n\n": 237,
	"Suggested Topics":     189,
	"To:":                  96,
	"Transplant Surgery":   82,
	"Valid email required": 85,
	"Verification":         36,
	"Wallet":               135,
	"We may be sending emails to an old or incorrect email address. To see or change the email address associated with your account, log in to your Olmax account from a desktop computer and follow the steps below:": 158,
	"We will send a reset code to the email provided": 123,
	"We'll only send the emails you tell us you want. To check your email notification settings, log in to your Olmax account from a desktop computer and follow the steps below:": 163,
	"We're there at every step": 218,
	"Welcome back!":             114,
	"Welcome patients":          223,
	"What are patients saying about our doctors from":                112,
	"What does each appointment status mean?":                        201,
	"What happens if my appointment request is declined or expires?": 154,
	"What is Bitcoin?":                                            192,
	"What is Bitcoin? ":                                           205,
	"What is a Verified Medical License?":                         197,
	"What is your biological gender?":                             9,
	"What makes your symptoms better, and What makes them worse?": 15,
	"When did your symptoms start?":                               11,
	"When were you born?":                                         8,
	"When will I be charged?":                                     182,
	"Where are your symptoms located? <i>part of your body</i>":   12,
	"Who We Are":                              101,
	"Why become a provider on Olmax?":         214,
	"Why did I not get a notification email?": 233,
	"Why didn't I get my email notification?": 196,
	"With Olmax, you're in full control of your availability, prices, medical management, and how you interact with patients. You can set appointment times and handle the process however you like.": 217,
	"Work with us!": 40,
	"Yes, you must submit payment in order to secure appointment contract. Your payment will be held in escrow until the visit is finalized. Once you submit fees, we will contact the physician and give him or her your medical information. The doctor will then confirm appointment, and an email or text will be sent to you, along with the physicians contact information. Fees are structured in amount of bitcoin (BTC) per unit(U) time (BTC/U). Every unit (U) is equivalent to 15 min, time spent in visit will be pre-determined, and visits going longer that what was agreed upon will not cost extra. All new consults must be a minimum of 2 units, and repeat visits can be a minimum of 1 unit.": 181,
	"You can bypass their firewall using tunnel software such as a VPN or Tor software. See the following for more information: ":   206,
	"You can bypass their firewall using tunnel software such as a VPN,  or Tor software. See the following for more information: ": 176,
	"You can bypass their firewall using tunnel software such as a VPN, or Tor software. See the following for more information: ":  186,
	"You currently have no appointments pending.":                                    1,
	"You currently have no messages.":                                                120,
	"You may make contact with your doctor as soon as the appointment is confirmed.": 179,
	"You're in control": 216,
}

var en_USIndex = []uint32{ // 240 elements
	// Entry 0 - 1F
	0x00000000, 0x0000001d, 0x00000049, 0x000000be,
	0x000000d6, 0x000000e1, 0x00000100, 0x00000117,
	0x0000014e, 0x00000162, 0x00000182, 0x000001dd,
	0x000001fb, 0x00000235, 0x0000025a, 0x000002ad,
	0x000002e9, 0x00000328, 0x00000379, 0x0000038f,
	0x000003af, 0x000003c6, 0x000003d7, 0x000003eb,
	0x00000404, 0x00000419, 0x0000043d, 0x00000469,
	0x0000049e, 0x000004a3, 0x000004aa, 0x000004f9,
	// Entry 20 - 3F
	0x000004fd, 0x00000502, 0x00000515, 0x00000525,
	0x00000535, 0x00000542, 0x0000054f, 0x00000555,
	0x00000564, 0x00000572, 0x00000583, 0x0000059e,
	0x000005b7, 0x000005ca, 0x000005e8, 0x000005ff,
	0x0000061b, 0x0000062f, 0x0000063e, 0x00000650,
	0x0000065b, 0x00000669, 0x00000676, 0x00000684,
	0x00000690, 0x000006a3, 0x000006b1, 0x000006c5,
	0x000006d5, 0x000006e9, 0x000006f7, 0x0000070f,
	// Entry 40 - 5F
	0x0000071a, 0x00000725, 0x00000730, 0x00000744,
	0x00000756, 0x00000762, 0x0000076d, 0x00000777,
	0x00000784, 0x0000079e, 0x000007b4, 0x000007c0,
	0x000007d3, 0x000007e3, 0x000007ee, 0x000007f7,
	0x00000803, 0x0000080d, 0x0000081f, 0x00000832,
	0x00000852, 0x00000877, 0x0000088c, 0x0000089a,
	0x000008ad, 0x000008d5, 0x000008ed, 0x000008fb,
	0x00000903, 0x0000090d, 0x0000091b, 0x0000092e,
	// Entry 60 - 7F
	0x00000934, 0x00000938, 0x0000094a, 0x00000956,
	0x00000960, 0x00000967, 0x00000972, 0x00000d4f,
	0x00000d5f, 0x00000f69, 0x00000f73, 0x00001005,
	0x00001030, 0x0000109a, 0x000010a2, 0x00001135,
	0x0000113e, 0x0000116e, 0x00001184, 0x00001192,
	0x00001199, 0x000011a3, 0x000011b9, 0x000011bf,
	0x000011d8, 0x000011f8, 0x00001216, 0x00001222,
	0x00001252, 0x00001258, 0x00001270, 0x00001281,
	// Entry 80 - 9F
	0x0000128d, 0x000012a3, 0x000012b8, 0x000012c3,
	0x000012d7, 0x000012f1, 0x000012f9, 0x00001310,
	0x00001317, 0x0000131d, 0x0000133f, 0x0000134d,
	0x00001375, 0x000013d3, 0x000013e5, 0x0000140c,
	0x00001423, 0x00001437, 0x00001460, 0x00001473,
	0x0000149b, 0x000014af, 0x000014c4, 0x00001501,
	0x00001603, 0x00001646, 0x000016f9, 0x00001738,
	0x000017cc, 0x00001809, 0x00001831, 0x00001902,
	// Entry A0 - BF
	0x0000191a, 0x00001963, 0x000019a3, 0x000019ca,
	0x00001a77, 0x00001a9d, 0x00001b05, 0x00001b74,
	0x00001b9c, 0x00001c5e, 0x00001c86, 0x00001cf1,
	0x00001d1f, 0x00001d85, 0x00001e47, 0x00001f5b,
	0x00001f81, 0x00002003, 0x0000201f, 0x00002034,
	0x00002083, 0x000020b6, 0x00002364, 0x0000237c,
	0x000023c4, 0x000023e1, 0x000023e5, 0x00002466,
	0x0000247b, 0x0000248c, 0x0000249d, 0x000024e2,
	// Entry C0 - DF
	0x0000250c, 0x0000251d, 0x0000253a, 0x0000257f,
	0x000025a0, 0x000025c8, 0x000025ec, 0x000025fa,
	0x0000262a, 0x00002641, 0x00002669, 0x00002690,
	0x0000269a, 0x000026bd, 0x000026d3, 0x00002753,
	0x0000279d, 0x00002890, 0x00002893, 0x000028b5,
	0x000028c7, 0x000028e4, 0x000028f0, 0x00002910,
	0x000029b7, 0x000029c9, 0x00002a89, 0x00002aa3,
	0x00002b33, 0x00002b53, 0x00002b67, 0x00002c13,
	// Entry E0 - FF
	0x00002c24, 0x00002c71, 0x00002c7a, 0x00002d93,
	0x00002da3, 0x00002dbb, 0x00002ede, 0x00002ef4,
	0x00002f87, 0x00002ff9, 0x00003021, 0x0000304f,
	0x00003082, 0x000030be, 0x000030f5, 0x0000313c,
} // Size: 984 bytes

const en_USData string = "" + // Size: 12604 bytes
	"\x02Olmax Medical | Appointments\x02You currently have no appointments p" +
	"ending.\x02If you have submitted payment, and do not see appointment sch" +
	"eduled on this page; please refer to the %[1]s section.\x02Olmax Medical" +
	" | Profile\x04\x00\x01 \x06\x02Hello\x02Olmax Medical | Create Profile" +
	"\x02Create Patient Profile\x02Please submit some information regarding y" +
	"our consult.\x02When were you born?\x02What is your biological gender?" +
	"\x02Please give a brief statement regarding the main reason you would li" +
	"ke to see your doctor:\x02When did your symptoms start?\x02Where are you" +
	"r symptoms located? <i>part of your body</i>\x02How long have these symp" +
	"toms lasted?\x02How would you characterize your symptoms? <i>Sharp, Dull" +
	", Ache, twisting, ets.</i>\x02What makes your symptoms better, and What " +
	"makes them worse?\x02Does your pain travel or radiate to another part of" +
	" your body?\x02Have you taken any medications for these symptoms and how" +
	" much have they worked?\x02Any fevers or Chills?\x02Any weight gain or w" +
	"eight loss?\x02Any changes in vision?\x02Any lung issues?\x02Any heart p" +
	"roblems?\x02Any intestinal problems?\x02Any kidney problems?\x02Any prob" +
	"lems with muscles or bones?\x02Any nervous system problmes? <i>Strokes</" +
	"i>\x02Any psychiatric problems? <i>Depression, anxiety</i>\x02Male\x02Fe" +
	"male\x02Please check any of the following if you have experienced in the" +
	" last 6 weeks:\x02FAQ\x02Help\x02Quality Healthcare\x02Payment Methods" +
	"\x02Prices and Fees\x02Verification\x02Appointments\x02Legal\x02Privacy " +
	"Policy\x02Work with us!\x02Become A Partner\x02Copyright 2017, 2018, 201" +
	"9\x02Olmax Medical | Bookings\x02Available patients\x02Olmax Medical | F" +
	"ind Patients\x02No selection for %[1]s\x02Invalid selection for %[1]s" +
	"\x02Acute Pain Medicine\x02Anesthesiology\x02Bariatric Surgery\x02Cardio" +
	"logy\x02Chiropractics\x02Chronic Pain\x02Critical Care\x02Dermatology" +
	"\x02Emergency Medicine\x02Endocrinology\x02Ear Nose and Throat\x02Family" +
	" Medicine\x02Gastrointestinology\x02Head and Neck\x02Hematology and Onco" +
	"logy\x02Hepatology\x02Hyperbaric\x02Immunology\x02Infectious Diseases" +
	"\x02Internal Medicine\x02Neonatology\x02Nephrology\x02Neurology\x02Neuro" +
	"surgery\x02Obstetrics and Gynecology\x02Occupational Medicine\x02Opthamo" +
	"logy\x02Orthopedic Surgery\x02Palliative Care\x02Pediatrics\x02Podiatry" +
	"\x02Pulmonology\x02Radiology\x02Radiaton Oncology\x02Transplant Surgery" +
	"\x02No selection for question %[1]d\x02Invalid selection for question %[" +
	"1]d\x02Valid email required\x02Invalid email\x02Full name required\x02Fu" +
	"ll name must be at least 2 characters\x02Olmax Medical | Welcome\x02Olma" +
	"x Medical\x02Country\x02Specialty\x02Find a Doctor\x02Appointment Dates:" +
	"\x02From:\x02To:\x02Appointment Times\x02Start Time:\x02End Time:\x02Sea" +
	"rch\x02Who We Are\x02Olmax Medical is a world wide network of physicians" +
	" and patients that enables them to communicate, meet virtually, and nego" +
	"tiate payment on a peer to peer basis, without the interference of insur" +
	"ance giants. We provide a platform where the economics of <i>laissez-fai" +
	"redes</i> (free-trade) will allow both physicians and patients to negoti" +
	"ate fee for service. Our website provide a platform where both patients " +
	"and doctors form around the world can deploy customized contracts descri" +
	"bing, in detail, the terms of health care. The cost, time, and duration " +
	"of virtual clinic visits will be pre-determined on contracts posted on o" +
	"ur website. The contracts are written by either doctor or patient. Contr" +
	"acts can be created, bought, and sold by anyone, because we believe heal" +
	"th care should be available to everyone. It will be our work to investig" +
	"ate and verify physician status. Once doctors are verified, patients wil" +
	"l have the opportunity to rate physician performance and bedside manners" +
	".\x02Second Opinions\x02Since the time of Hippocrates, patients and doct" +
	"ors were limited to serving and receiving care from physician in their m" +
	"ore local community. With our platform patients will not be tied to HMOs" +
	" or managed health care. In other words, insurance companies or governme" +
	"nt decisions will no longer chain patients to the type and quality of he" +
	"alth care they receive. Doctors with extremely rare specialties will be " +
	"able to serve communities thousands of miles away from them, and from th" +
	"e comfort of their home if they so desire\x02Anonymity\x02Patients will " +
	"be encouraged to use anonymous names. Medical records are kept between p" +
	"atients and physicians, they are not stored on our servers.\x02Access to" +
	" Physicians from around the world\x02Physicians from around the world wi" +
	"ll be able to join our network, see patients from anywhere at anytime." +
	"\x02Payment\x02Payments will be made with Bitcoin. Minimal fees will be " +
	"charged by our website for holding the cryptocurrency until clinical vis" +
	"its are complete.\x02See More\x02What are patients saying about our doct" +
	"ors from\x02Olmax Medical | Login\x02Welcome back!\x02Email:\x02Password" +
	":\x02Forgot your password?\x02Login\x02Olmax Medical | Messages\x02You c" +
	"urrently have no messages.\x02Previous messages: Click here\x02Enter Ema" +
	"il\x02We will send a reset code to the email provided\x02Reset\x02Olmax " +
	"Medical | Sign Up\x02Sign Up for free\x02First Name:\x02Enter your first" +
	" name\x02Enter your last name\x02Last Name:\x02Enter a valid email\x02En" +
	"ter password (8+ chars)\x02Sign Up\x02Olmax Medical | Wallet\x02Wallet" +
	"\x020 BTC\x02NO FUNDS CURRENTLY HELD IN ESCROW\x02Deposit Funds\x02Send " +
	"only Bitcoin (BTC) to this address\x02Sending any other digital asset, i" +
	"ncluding Bitcoin Cash (BCH), will result in permanent loss.\x02Password " +
	"required\x02Password must be at least 8 characters\x02Re-enter same pass" +
	"word\x02First name required\x02First name must be at least 2 characters" +
	"\x02Last name required\x02Last name must be at least 2 characters\x02Olm" +
	"ax Medical | FAQ\x02Appointment Requests\x02I am a patient. How do I che" +
	"ck the status of my appointment?\x02Once an appointment request is submi" +
	"tted, the physician has 4 to 12 hrs to replay. Depending on the urgency." +
	" If you would like a reply within 4 hr for urgent consults, an extra fee" +
	" can be payed. Otherwise doctors have 12 hrs to reply to appointment req" +
	"uest.\x02Should I clear my schedule if I have no heard back from my doct" +
	"or?\x02If you do not recieve a confimation email by 12 hrs, then a full " +
	"refund will be returned to your bitcoin account along with an email stat" +
	"ing that an appointment could not be made\x02What happens if my appointm" +
	"ent request is declined or expires?\x02If you recieve an email confirmin" +
	"g a cancelation of decline, bitcoin will be returned to your account inf" +
	"ull, then you may seek another appointment\x02I did not recieve an email" +
	" confirming nor denying my request\x02Make sure your email address is co" +
	"rrect\x02We may be sending emails to an old or incorrect email address. " +
	"To see or change the email address associated with your account, log in " +
	"to your Olmax account from a desktop computer and follow the steps below" +
	":\x021.) Go to Edit Profile.\x022.) Look for the Email Address field. Ma" +
	"ke sure your address is correct.\x023.) If it is incorrect, add the corr" +
	"ect address and click Save.\x02Check your email notification settings" +
	"\x02We'll only send the emails you tell us you want. To check your email" +
	" notification settings, log in to your Olmax account from a desktop comp" +
	"uter and follow the steps below:\x021.) Go to your Notification Settings" +
	".\x022.) Look for the \x22Email Settings\x22 field. Make sure you have c" +
	"hosen the email types you want to receive.\x023.) After adding or removi" +
	"ng checkmarks from the right boxes, scroll to the bottom of the page and" +
	" click Save.\x02Search all messages in your email inbox\x02Sometimes ema" +
	"ils can get lost in your inbox. In your email account, search for terms " +
	"like \x22Olmax Medical\x22, \x22Appointment\x22, \x22Verification\x22, o" +
	"r other words related to the email you're looking for.\x02Check your spa" +
	"m and other email filters\x02It's possible your email provider mistakenl" +
	"y sent our messages to your spam or junk folder. To avoid this:\x021.) R" +
	"emove Olmax messages from your spam list\x022.) Add nemo@olmax.com, half" +
	"wit@olmax.com, and services@olmax.com to your personal email address boo" +
	"k\x02If you have other filters or routing rules in your email account th" +
	"at may have sorted Olmax emails elsewhere, be sure to check those, too.<" +
	"/br>Check for issues with your email service provider.\x02Depending on y" +
	"our provider, emails can take up to a few hours to be delivered. If unde" +
	"livered or delayed emails continue to be an issue, check with your provi" +
	"der to see if there are any configuration issues or problems with their " +
	"network that might be affecting your account.\x02If your country blocks " +
	"Olmax Medical?\x04\x00\x01 }\x02You can bypass their firewall using tunn" +
	"el software such as a VPN,  or Tor software. See the following for more " +
	"information:\x02Olmax Medical | Our Doctors\x02Contacting Physician\x02Y" +
	"ou may make contact with your doctor as soon as the appointment is confi" +
	"rmed.\x02Do I need to pay before scheduling an appointment?\x02Yes, you " +
	"must submit payment in order to secure appointment contract. Your paymen" +
	"t will be held in escrow until the visit is finalized. Once you submit f" +
	"ees, we will contact the physician and give him or her your medical info" +
	"rmation. The doctor will then confirm appointment, and an email or text " +
	"will be sent to you, along with the physicians contact information. Fees" +
	" are structured in amount of bitcoin (BTC) per unit(U) time (BTC/U). Eve" +
	"ry unit (U) is equivalent to 15 min, time spent in visit will be pre-det" +
	"ermined, and visits going longer that what was agreed upon will not cost" +
	" extra. All new consults must be a minimum of 2 units, and repeat visits" +
	" can be a minimum of 1 unit.\x02When will I be charged?\x02Bitcoin must " +
	"be paid in full upon deployment or acceptance of contract.\x02Can I pay " +
	"with any currency?\x02No.\x04\x00\x01 |\x02You can bypass their firewall" +
	" using tunnel software such as a VPN, or Tor software. See the following" +
	" for more information:\x02Olmax Medical | Help\x02How can we help?\x02Su" +
	"ggested Topics\x02Should I clear my schedule if I have not heard back fr" +
	"om the doctor?\x02How do I edit or remove a payment method?\x02What is B" +
	"itcoin?\x02How do I use Bitcoin to pay?\x02How can I add another appoint" +
	"ment or business address to my receipt?\x02How do I verify my phone numb" +
	"er?\x02Why didn't I get my email notification?\x02What is a Verified Med" +
	"ical License?\x02Prices & Fees\x02How is the price determined for my app" +
	"ointment?\x02Contacting A Physician\x02What does each appointment status" +
	" mean?\x02How do I make an appointment on Olmax?\x02-View all\x04\x00" +
	"\x01 \x1e\x02All payments will be done via\x04\x00\x01 \x11\x02What is B" +
	"itcoin?\x04\x00\x01 {\x02You can bypass their firewall using tunnel soft" +
	"ware such as a VPN or Tor software. See the following for more informati" +
	"on:\x02Prices and fees are for the most part determined by doctors and p" +
	"atients.\x02Prices are set by who deploys the contract (doctor or patien" +
	"t). Fees are structured in a amount of bitcoin (BTC) per unit. In which " +
	"a unit of time equals 15 mins. All new consults must be a minimum of 2 u" +
	"nits, and repeat visits can be 1 unit.\x02No\x02Olmax Medical | Become A" +
	" Provider\x02Become A Provider\x02Find out what you could earn\x02Get St" +
	"arted\x02Why become a provider on Olmax?\x02No matter what your specialt" +
	"y, Olmax makes it simple and secure to reach millions of patients lookin" +
	"g for doctors with unique skills and specialties, just like yours.\x02Yo" +
	"u're in control\x02With Olmax, you're in full control of your availabili" +
	"ty, prices, medical management, and how you interact with patients. You " +
	"can set appointment times and handle the process however you like.\x02We" +
	"'re there at every step\x02Olmax offers tools, service tips, 24/7 suppor" +
	"t, and an on-line community of experienced physicians for questions and " +
	"sharing ideas for success.\x02How to become an Olmax Provider\x02Create " +
	"your profile\x02It's free and easy to create a profile on Olmax. Describ" +
	"e your resume, how many patients you can accomodate, set your own times," +
	" and add photos and details about yourself.\x02Welcome patients\x02Commu" +
	"nicate with patients via 3rd party applications, or personal telephone." +
	"\x02Get Paid\x02Olmax's secure payment system means you will never see a" +
	" patient without compensation, or have to deal with money directly. Pati" +
	"enst are charged before appointments, and you are paid after the visit i" +
	"s completed. We embrace the future, therefore payments will be via Bitco" +
	"in only.\x02Safety on Olmax\x02Olmax is built on trust\x02All Olmax phys" +
	"icians must: submit a profile photo, medical diplomas, residency certifi" +
	"cation or equivalent, verify their phone, email, government ID, and back" +
	"ground checks. Patients and physicians can each publish reviews after vi" +
	"sit conclusions keeping everyone accountable and respectful.\x02Start se" +
	"eing patients\x02Profile information such as government ID, diplomas, ph" +
	"one numbers, and emails will will be verified before being posted on Olm" +
	"ax Medical website.\x02Once you have submitted a phone number, you can e" +
	"ither receive a text message or call with a confirmation number.\x02Why " +
	"did I not get a notification email?\x04\x00\x01 )\x02Please refer to the" +
	" following help page:\x04\x00\x02\x0a\x0a-\x02Subject: Olmax Medical - R" +
	"eset Your Password\x04\x00\x01 7\x02Please click the following link to r" +
	"eset your password\x04\x00\x02\x0a\x0a1\x02Subject: Olmax Medical - Veri" +
	"fy your new account\x04\x00\x01 B\x02Please click the following link to " +
	"finalize your account creation"

	// Total table size 13588 bytes (13KiB); checksum: B1B6FDC
