// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p := messageKeyToIndex[key]
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"-View all":                             155,
	"0 BTC":                                 237,
	"1.) Go to Edit Profile.":               111,
	"1.) Go to your Notification Settings.": 116,
	"1.) Remove Olmax messages from your spam list":                                                                  123,
	"2.) Add nemo@olmax.com, halfwit@olmax.com, and services@olmax.com to your personal email address book":          124,
	"2.) Look for the \"Email Settings\" field. Make sure you have chosen the email types you want to receive.":      117,
	"2.) Look for the Email Address field. Make sure your address is correct.":                                       112,
	"3.) After adding or removing checkmarks from the right boxes, scroll to the bottom of the page and click Save.": 118,
	"3.) If it is incorrect, add the correct address and click Save.":                                                113,
	"About Us": 58,
	"Access to Physicians from around the world": 208,
	"Acute Pain Medicine":                        64,
	"All Olmax physicians must: submit a profile photo, medical diplomas, residency certification or equivalent, verify their phone, email, government ID, and background checks. Patients and physicians can each publish reviews after visit conclusions keeping everyone accountable and respectful.": 182,
	"All payments will be done via ":                       156,
	"Anesthesiology":                                       65,
	"Anonymity":                                            206,
	"Any changes in vision?":                               24,
	"Any fevers or Chills?":                                22,
	"Any heart problems?":                                  26,
	"Any intestinal problems?":                             27,
	"Any kidney problems?":                                 28,
	"Any lung issues?":                                     25,
	"Any nervous system problmes? <i>Strokes</i>":          30,
	"Any problems with muscles or bones?":                  29,
	"Any psychiatric problems? <i>Depression, anxiety</i>": 31,
	"Any weight gain or weight loss?":                      23,
	"Appointment Dates:":                                   195,
	"Appointment Requests":                                 101,
	"Appointment Times":                                    198,
	"Appointments":                                         55,
	"Are You A Doctor?":                                    62,
	"Available patients":                                   47,
	"Bariatric Surgery":                                    66,
	"Become A Partner":                                     61,
	"Become A Provider":                                    164,
	"Bitcoin must be paid in full upon deployment or acceptance of contract.": 135,
	"Can I pay with any currency?":                                            136,
	"Cardiology":                                                              67,
	"Check your email notification settings":                                  114,
	"Check your spam and other email filters":                                 121,
	"Chiropractics":                                                           68,
	"Chronic Pain":                                                            69,
	"Communicate with patients via 3rd party applications, or personal telephone.": 177,
	"Contacting A Physician":     152,
	"Contacting Physician":       130,
	"Copyright 2017, 2018, 2019": 63,
	"Country":                    193,
	"Create Patient Profile":     10,
	"Create your profile":        174,
	"Critical Care":              70,
	"Depending on your provider, emails can take up to a few hours to be delivered. If undelivered or delayed emails continue to be an issue, check with your provider to see if there are any configuration issues or problems with their network that might be affecting your account.": 126,
	"Deposit Funds": 239,
	"Dermatology":   71,
	"Do I need to pay before scheduling an appointment?":             132,
	"Does your pain travel or radiate to another part of your body?": 20,
	"Ear Nose and Throat":          74,
	"Email:":                       216,
	"Emergency Medicine":           72,
	"End Time:":                    200,
	"Endocrinology":                73,
	"Enter Email":                  223,
	"Enter a valid email":          232,
	"Enter password (8+ chars)":    233,
	"Enter your first name":        229,
	"Enter your last name":         230,
	"FAQ":                          49,
	"Family Medicine":              75,
	"Female":                       33,
	"Find a Doctor":                194,
	"Find out what you could earn": 165,
	"First Name:":                  228,
	"First name must be at least 2 characters": 41,
	"First name required":                      40,
	"Forgot your password?":                    218,
	"From:":                                    196,
	"Full name must be at least 2 characters":  191,
	"Full name required":                       190,
	"Gastrointestinology":                      76,
	"Get Paid":                                 178,
	"Get Started":                              166,
	"Have you taken any medications for these symptoms and how much have they worked?": 21,
	"Head and Neck":           77,
	"Hello ":                  8,
	"Help":                    50,
	"Hematology and Oncology": 78,
	"Hepatology":              79,
	"How can I add another appointment or business address to my receipt?": 146,
	"How can we help?":                                                                   140,
	"How do I edit or remove a payment method?":                                          143,
	"How do I make an appointment on Olmax?":                                             154,
	"How do I use Bitcoin to pay?":                                                       145,
	"How do I verify my phone number?":                                                   147,
	"How is the price determined for my appointment?":                                    151,
	"How long have these symptoms lasted?":                                               17,
	"How to become an Olmax Provider":                                                    173,
	"How would you characterize your symptoms? <i>Sharp, Dull, Ache, twisting, ets.</i>": 18,
	"Hyperbaric": 80,
	"I am a patient. How do I check the status of my appointment?": 102,
	"I did not recieve an email confirming nor denying my request": 108,
	"If you do not recieve a confimation email by 12 hrs, then a full refund will be returned to your bitcoin account along with an email stating that an appointment could not be made":                105,
	"If you have other filters or routing rules in your email account that may have sorted Olmax emails elsewhere, be sure to check those, too.</br>Check for issues with your email service provider.": 125,
	"If you have submitted payment, and do not see appointment scheduled on this page; please refer to the %s section.":                                                                                 6,
	"If you recieve an email confirming a cancelation of decline, bitcoin will be returned to your account infull, then you may seek another appointment":                                               107,
	"If your country blocks Olmax Medical?": 127,
	"Immunology":                            81,
	"Infectious Diseases":                   82,
	"Internal Medicine":                     83,
	"Invalid email":                         39,
	"Invalid selection for %s":              45,
	"Invalid selection for question %d":     189,
	"It's free and easy to create a profile on Olmax. Describe your resume, how many patients you can accomodate, set your own times, and add photos and details about yourself.": 175,
	"It's possible your email provider mistakenly sent our messages to your spam or junk folder. To avoid this:":                                                                  122,
	"Last Name:": 231,
	"Last name must be at least 2 characters": 43,
	"Last name required":                      42,
	"Legal":                                   56,
	"Login":                                   219,
	"Make sure your email address is correct": 109,
	"Male":                              32,
	"NO FUNDS CURRENTLY HELD IN ESCROW": 238,
	"Neonatology":                       84,
	"Nephrology":                        85,
	"Neurology":                         86,
	"Neurosurgery":                      87,
	"No":                                161,
	"No matter what your specialty, Olmax makes it simple and secure to reach millions of patients looking for doctors with unique skills and specialties, just like yours.": 168,
	"No selection for %s":          44,
	"No selection for question %d": 188,
	"No.":                          137,
	"Obstetrics and Gynecology":    88,
	"Occupational Medicine":        89,
	"Olmax":                        59,
	"Olmax Medical":                100,
	"Olmax Medical is a world wide network of physicians and patients that enables them to communicate, meet virtually, and negotiate payment on a peer to peer basis, without the interference of insurance giants. We provide a platform where the economics of <i>laissez-fairedes</i> (free-trade) will allow both physicians and patients to negotiate fee for service. Our website provide a platform where both patients and doctors form around the world can deploy customized contracts describing, in detail, the terms of health care. The cost, time, and duration of virtual clinic visits will be pre-determined on contracts posted on our website. The contracts are written by either doctor or patient. Contracts can be created, bought, and sold by anyone, because we believe health care should be available to everyone. It will be our work to investigate and verify physician status. Once doctors are verified, patients will have the opportunity to rate physician performance and bedside manners.": 203,
	"Olmax Medical | Appointments":      4,
	"Olmax Medical | Become A Provider": 162,
	"Olmax Medical | Bookings":          46,
	"Olmax Medical | Create Profile":    9,
	"Olmax Medical | FAQ":               99,
	"Olmax Medical | Find Patients":     48,
	"Olmax Medical | Help":              139,
	"Olmax Medical | Login":             214,
	"Olmax Medical | Messages":          220,
	"Olmax Medical | Our Doctors":       129,
	"Olmax Medical | Profile":           7,
	"Olmax Medical | Sign Up":           226,
	"Olmax Medical | Wallet":            235,
	"Olmax Medical | Welcome":           192,
	"Olmax is built on trust":           181,
	"Olmax offers tools, service tips, 24/7 support, and an on-line community of experienced physicians for questions and sharing ideas for success.":                                                                                                                                          172,
	"Olmax's secure payment system means you will never see a patient without compensation, or have to deal with money directly. Patienst are charged before appointments, and you are paid after the visit is completed. We embrace the future, therefore payments will be via Bitcoin only.": 179,
	"Once an appointment request is submitted, the physician has 4 to 12 hrs to replay. Depending on the urgency. If you would like a reply within 4 hr for urgent consults, an extra fee can be payed. Otherwise doctors have 12 hrs to reply to appointment request.":                        103,
	"Once you have submitted a phone number, you can either receive a text message or call with a confirmation number.":                                                                                                                                                                        185,
	"Opthamology":                            90,
	"Orthopedic Surgery":                     91,
	"Over 12B patients served":               51,
	"Palliative Care":                        92,
	"Partnering":                             60,
	"Password must be at least 8 characters": 36,
	"Password required":                      35,
	"Password:":                              217,
	"Patients will be encouraged to use anonymous names. Medical records are kept between patients and physicians, they are not stored on our servers.": 207,
	"Payment":         210,
	"Payment Methods": 52,
	"Payments will be made with Bitcoin. Minimal fees will be charged by our website for holding the cryptocurrency until clinical visits are complete.": 211,
	"Pediatrics": 93,
	"Physicians from around the world will be able to join our network, see patients from anywhere at anytime.": 209,
	"Please check any of the following if you have experienced in the last 6 weeks:":                            34,
	"Please click the following link to finalize your account creation ":                                        3,
	"Please click the following link to reset your password ":                                                   1,
	"Please give a brief statement regarding the main reason you would like to see your doctor:":                14,
	"Please refer to the following help page: ":                                                                 187,
	"Please submit some information regarding your consult.":                                                    11,
	"Podiatry":                      94,
	"Previous messages: Click here": 222,
	"Prices & Fees":                 150,
	"Prices and Fees":               53,
	"Prices and fees are for the most part determined by doctors and patients.": 159,
	"Prices are set by who deploys the contract (doctor or patient). Fees are structured in a amount of bitcoin (BTC) per unit. In which a unit of time equals 15 mins. All new consults must be a minimum of 2 units, and repeat visits can be 1 unit.": 160,
	"Privacy Policy": 57,
	"Profile information such as government ID, diplomas, phone numbers, and emails will will be verified before being posted on Olmax Medical website.": 184,
	"Pulmonology":            95,
	"Radiaton Oncology":      97,
	"Radiology":              96,
	"Re-enter same password": 37,
	"Reset":                  225,
	"Safety on Olmax":        180,
	"Search":                 201,
	"Search all messages in your email inbox": 119,
	"Second Opinions":                         204,
	"See More":                                212,
	"Send only Bitcoin (BTC) to this address": 240,
	"Sending any other digital asset, including Bitcoin Cash (BCH), will result in permanent loss.": 241,
	"Should I clear my schedule if I have no heard back from my doctor?":                            104,
	"Should I clear my schedule if I have not heard back from the doctor?":                          142,
	"Sign Up":          234,
	"Sign Up for free": 227,
	"Since the time of Hippocrates, patients and doctors were limited to serving and receiving care from physician in their more local community. With our platform patients will not be tied to HMOs or managed health care. In other words, insurance companies or government decisions will no longer chain patients to the type and quality of health care they receive. Doctors with extremely rare specialties will be able to serve communities thousands of miles away from them, and from the comfort of their home if they so desire": 205,
	"Sometimes emails can get lost in your inbox. In your email account, search for terms like \"Olmax Medical\", \"Appointment\", \"Verification\", or other words related to the email you're looking for.": 120,
	"Specialty":             163,
	"Start Time:":           199,
	"Start seeing patients": 183,
	"Subject: Olmax Medical - Reset Your Password\n\n":     0,
	"Subject: Olmax Medical - Verify your new account\n\n": 2,
	"Suggested Topics":     141,
	"To:":                  197,
	"Transplant Surgery":   98,
	"Valid email required": 38,
	"Verification":         54,
	"Wallet":               236,
	"We may be sending emails to an old or incorrect email address. To see or change the email address associated with your account, log in to your Olmax account from a desktop computer and follow the steps below:": 110,
	"We will send a reset code to the email provided": 224,
	"We'll only send the emails you tell us you want. To check your email notification settings, log in to your Olmax account from a desktop computer and follow the steps below:": 115,
	"We're there at every step": 171,
	"Welcome back!":             215,
	"Welcome patients":          176,
	"What are patients saying about our doctors from":                213,
	"What does each appointment status mean?":                        153,
	"What happens if my appointment request is declined or expires?": 106,
	"What is Bitcoin?":                                            144,
	"What is Bitcoin? ":                                           157,
	"What is a Verified Medical License?":                         149,
	"What is your biological gender?":                             13,
	"What makes your symptoms better, and What makes them worse?": 19,
	"When did your symptoms start?":                               15,
	"When were you born?":                                         12,
	"When will I be charged?":                                     134,
	"Where are your symptoms located? <i>part of your body</i>":   16,
	"Who We Are":                              202,
	"Why become a provider on Olmax?":         167,
	"Why did I not get a notification email?": 186,
	"Why didn't I get my email notification?": 148,
	"With Olmax, you're in full control of your availability, prices, medical management, and how you interact with patients. You can set appointment times and handle the process however you like.": 170,
	"Yes, you must submit payment in order to secure appointment contract. Your payment will be held in escrow until the visit is finalized. Once you submit fees, we will contact the physician and give him or her your medical information. The doctor will then confirm appointment, and an email or text will be sent to you, along with the physicians contact information. Fees are structured in amount of bitcoin (BTC) per unit(U) time (BTC/U). Every unit (U) is equivalent to 15 min, time spent in visit will be pre-determined, and visits going longer that what was agreed upon will not cost extra. All new consults must be a minimum of 2 units, and repeat visits can be a minimum of 1 unit.": 133,
	"You can bypass their firewall using tunnel software such as a VPN or Tor software. See the following for more information: ":   158,
	"You can bypass their firewall using tunnel software such as a VPN,  or Tor software. See the following for more information: ": 128,
	"You can bypass their firewall using tunnel software such as a VPN, or Tor software. See the following for more information: ":  138,
	"You currently have no appointments pending.":                                    5,
	"You currently have no messages.":                                                221,
	"You may make contact with your doctor as soon as the appointment is confirmed.": 131,
	"You're in control": 169,
}

var en_USIndex = []uint32{ // 243 elements
	// Entry 0 - 1F
	0x00000000, 0x00000033, 0x0000006f, 0x000000a6,
	0x000000ed, 0x0000010a, 0x00000136, 0x000001ab,
	0x000001c3, 0x000001ce, 0x000001ed, 0x00000204,
	0x0000023b, 0x0000024f, 0x0000026f, 0x000002ca,
	0x000002e8, 0x00000322, 0x00000347, 0x0000039a,
	0x000003d6, 0x00000415, 0x00000466, 0x0000047c,
	0x0000049c, 0x000004b3, 0x000004c4, 0x000004d8,
	0x000004f1, 0x00000506, 0x0000052a, 0x00000556,
	// Entry 20 - 3F
	0x0000058b, 0x00000590, 0x00000597, 0x000005e6,
	0x000005f8, 0x0000061f, 0x00000636, 0x0000064b,
	0x00000659, 0x0000066d, 0x00000696, 0x000006a9,
	0x000006d1, 0x000006e8, 0x00000704, 0x0000071d,
	0x00000730, 0x0000074e, 0x00000752, 0x00000757,
	0x00000770, 0x00000780, 0x00000790, 0x0000079d,
	0x000007aa, 0x000007b0, 0x000007bf, 0x000007c8,
	0x000007ce, 0x000007d9, 0x000007ea, 0x000007fc,
	// Entry 40 - 5F
	0x00000817, 0x0000082b, 0x0000083a, 0x0000084c,
	0x00000857, 0x00000865, 0x00000872, 0x00000880,
	0x0000088c, 0x0000089f, 0x000008ad, 0x000008c1,
	0x000008d1, 0x000008e5, 0x000008f3, 0x0000090b,
	0x00000916, 0x00000921, 0x0000092c, 0x00000940,
	0x00000952, 0x0000095e, 0x00000969, 0x00000973,
	0x00000980, 0x0000099a, 0x000009b0, 0x000009bc,
	0x000009cf, 0x000009df, 0x000009ea, 0x000009f3,
	// Entry 60 - 7F
	0x000009ff, 0x00000a09, 0x00000a1b, 0x00000a2e,
	0x00000a42, 0x00000a50, 0x00000a65, 0x00000aa2,
	0x00000ba4, 0x00000be7, 0x00000c9a, 0x00000cd9,
	0x00000d6d, 0x00000daa, 0x00000dd2, 0x00000ea3,
	0x00000ebb, 0x00000f04, 0x00000f44, 0x00000f6b,
	0x00001018, 0x0000103e, 0x000010a6, 0x00001115,
	0x0000113d, 0x000011ff, 0x00001227, 0x00001292,
	0x000012c0, 0x00001326, 0x000013e8, 0x000014fc,
	// Entry 80 - 9F
	0x00001522, 0x000015a4, 0x000015c0, 0x000015d5,
	0x00001624, 0x00001657, 0x00001905, 0x0000191d,
	0x00001965, 0x00001982, 0x00001986, 0x00001a07,
	0x00001a1c, 0x00001a2d, 0x00001a3e, 0x00001a83,
	0x00001aad, 0x00001abe, 0x00001adb, 0x00001b20,
	0x00001b41, 0x00001b69, 0x00001b8d, 0x00001b9b,
	0x00001bcb, 0x00001be2, 0x00001c0a, 0x00001c31,
	0x00001c3b, 0x00001c5e, 0x00001c74, 0x00001cf4,
	// Entry A0 - BF
	0x00001d3e, 0x00001e31, 0x00001e34, 0x00001e56,
	0x00001e60, 0x00001e72, 0x00001e8f, 0x00001e9b,
	0x00001ebb, 0x00001f62, 0x00001f74, 0x00002034,
	0x0000204e, 0x000020de, 0x000020fe, 0x00002112,
	0x000021be, 0x000021cf, 0x0000221c, 0x00002225,
	0x0000233e, 0x0000234e, 0x00002366, 0x00002489,
	0x0000249f, 0x00002532, 0x000025a4, 0x000025cc,
	0x000025fa, 0x0000261a, 0x0000263f, 0x00002652,
	// Entry C0 - DF
	0x0000267a, 0x00002692, 0x0000269a, 0x000026a8,
	0x000026bb, 0x000026c1, 0x000026c5, 0x000026d7,
	0x000026e3, 0x000026ed, 0x000026f4, 0x000026ff,
	0x00002adc, 0x00002aec, 0x00002cf6, 0x00002d00,
	0x00002d92, 0x00002dbd, 0x00002e27, 0x00002e2f,
	0x00002ec2, 0x00002ecb, 0x00002efb, 0x00002f11,
	0x00002f1f, 0x00002f26, 0x00002f30, 0x00002f46,
	0x00002f4c, 0x00002f65, 0x00002f85, 0x00002fa3,
	// Entry E0 - FF
	0x00002faf, 0x00002fdf, 0x00002fe5, 0x00002ffd,
	0x0000300e, 0x0000301a, 0x00003030, 0x00003045,
	0x00003050, 0x00003064, 0x0000307e, 0x00003086,
	0x0000309d, 0x000030a4, 0x000030aa, 0x000030cc,
	0x000030da, 0x00003102, 0x00003160,
} // Size: 996 bytes

const en_USData string = "" + // Size: 12640 bytes
	"\x04\x00\x02\x0a\x0a-\x02Subject: Olmax Medical - Reset Your Password" +
	"\x04\x00\x01 7\x02Please click the following link to reset your password" +
	"\x04\x00\x02\x0a\x0a1\x02Subject: Olmax Medical - Verify your new accoun" +
	"t\x04\x00\x01 B\x02Please click the following link to finalize your acco" +
	"unt creation\x02Olmax Medical | Appointments\x02You currently have no ap" +
	"pointments pending.\x02If you have submitted payment, and do not see app" +
	"ointment scheduled on this page; please refer to the %[1]s section.\x02O" +
	"lmax Medical | Profile\x04\x00\x01 \x06\x02Hello\x02Olmax Medical | Crea" +
	"te Profile\x02Create Patient Profile\x02Please submit some information r" +
	"egarding your consult.\x02When were you born?\x02What is your biological" +
	" gender?\x02Please give a brief statement regarding the main reason you " +
	"would like to see your doctor:\x02When did your symptoms start?\x02Where" +
	" are your symptoms located? <i>part of your body</i>\x02How long have th" +
	"ese symptoms lasted?\x02How would you characterize your symptoms? <i>Sha" +
	"rp, Dull, Ache, twisting, ets.</i>\x02What makes your symptoms better, a" +
	"nd What makes them worse?\x02Does your pain travel or radiate to another" +
	" part of your body?\x02Have you taken any medications for these symptoms" +
	" and how much have they worked?\x02Any fevers or Chills?\x02Any weight g" +
	"ain or weight loss?\x02Any changes in vision?\x02Any lung issues?\x02Any" +
	" heart problems?\x02Any intestinal problems?\x02Any kidney problems?\x02" +
	"Any problems with muscles or bones?\x02Any nervous system problmes? <i>S" +
	"trokes</i>\x02Any psychiatric problems? <i>Depression, anxiety</i>\x02Ma" +
	"le\x02Female\x02Please check any of the following if you have experience" +
	"d in the last 6 weeks:\x02Password required\x02Password must be at least" +
	" 8 characters\x02Re-enter same password\x02Valid email required\x02Inval" +
	"id email\x02First name required\x02First name must be at least 2 charact" +
	"ers\x02Last name required\x02Last name must be at least 2 characters\x02" +
	"No selection for %[1]s\x02Invalid selection for %[1]s\x02Olmax Medical |" +
	" Bookings\x02Available patients\x02Olmax Medical | Find Patients\x02FAQ" +
	"\x02Help\x02Over 12B patients served\x02Payment Methods\x02Prices and Fe" +
	"es\x02Verification\x02Appointments\x02Legal\x02Privacy Policy\x02About U" +
	"s\x02Olmax\x02Partnering\x02Become A Partner\x02Are You A Doctor?\x02Cop" +
	"yright 2017, 2018, 2019\x02Acute Pain Medicine\x02Anesthesiology\x02Bari" +
	"atric Surgery\x02Cardiology\x02Chiropractics\x02Chronic Pain\x02Critical" +
	" Care\x02Dermatology\x02Emergency Medicine\x02Endocrinology\x02Ear Nose " +
	"and Throat\x02Family Medicine\x02Gastrointestinology\x02Head and Neck" +
	"\x02Hematology and Oncology\x02Hepatology\x02Hyperbaric\x02Immunology" +
	"\x02Infectious Diseases\x02Internal Medicine\x02Neonatology\x02Nephrolog" +
	"y\x02Neurology\x02Neurosurgery\x02Obstetrics and Gynecology\x02Occupatio" +
	"nal Medicine\x02Opthamology\x02Orthopedic Surgery\x02Palliative Care\x02" +
	"Pediatrics\x02Podiatry\x02Pulmonology\x02Radiology\x02Radiaton Oncology" +
	"\x02Transplant Surgery\x02Olmax Medical | FAQ\x02Olmax Medical\x02Appoin" +
	"tment Requests\x02I am a patient. How do I check the status of my appoin" +
	"tment?\x02Once an appointment request is submitted, the physician has 4 " +
	"to 12 hrs to replay. Depending on the urgency. If you would like a reply" +
	" within 4 hr for urgent consults, an extra fee can be payed. Otherwise d" +
	"octors have 12 hrs to reply to appointment request.\x02Should I clear my" +
	" schedule if I have no heard back from my doctor?\x02If you do not recie" +
	"ve a confimation email by 12 hrs, then a full refund will be returned to" +
	" your bitcoin account along with an email stating that an appointment co" +
	"uld not be made\x02What happens if my appointment request is declined or" +
	" expires?\x02If you recieve an email confirming a cancelation of decline" +
	", bitcoin will be returned to your account infull, then you may seek ano" +
	"ther appointment\x02I did not recieve an email confirming nor denying my" +
	" request\x02Make sure your email address is correct\x02We may be sending" +
	" emails to an old or incorrect email address. To see or change the email" +
	" address associated with your account, log in to your Olmax account from" +
	" a desktop computer and follow the steps below:\x021.) Go to Edit Profil" +
	"e.\x022.) Look for the Email Address field. Make sure your address is co" +
	"rrect.\x023.) If it is incorrect, add the correct address and click Save" +
	".\x02Check your email notification settings\x02We'll only send the email" +
	"s you tell us you want. To check your email notification settings, log i" +
	"n to your Olmax account from a desktop computer and follow the steps bel" +
	"ow:\x021.) Go to your Notification Settings.\x022.) Look for the \x22Ema" +
	"il Settings\x22 field. Make sure you have chosen the email types you wan" +
	"t to receive.\x023.) After adding or removing checkmarks from the right " +
	"boxes, scroll to the bottom of the page and click Save.\x02Search all me" +
	"ssages in your email inbox\x02Sometimes emails can get lost in your inbo" +
	"x. In your email account, search for terms like \x22Olmax Medical\x22, " +
	"\x22Appointment\x22, \x22Verification\x22, or other words related to the" +
	" email you're looking for.\x02Check your spam and other email filters" +
	"\x02It's possible your email provider mistakenly sent our messages to yo" +
	"ur spam or junk folder. To avoid this:\x021.) Remove Olmax messages from" +
	" your spam list\x022.) Add nemo@olmax.com, halfwit@olmax.com, and servic" +
	"es@olmax.com to your personal email address book\x02If you have other fi" +
	"lters or routing rules in your email account that may have sorted Olmax " +
	"emails elsewhere, be sure to check those, too.</br>Check for issues with" +
	" your email service provider.\x02Depending on your provider, emails can " +
	"take up to a few hours to be delivered. If undelivered or delayed emails" +
	" continue to be an issue, check with your provider to see if there are a" +
	"ny configuration issues or problems with their network that might be aff" +
	"ecting your account.\x02If your country blocks Olmax Medical?\x04\x00" +
	"\x01 }\x02You can bypass their firewall using tunnel software such as a " +
	"VPN,  or Tor software. See the following for more information:\x02Olmax " +
	"Medical | Our Doctors\x02Contacting Physician\x02You may make contact wi" +
	"th your doctor as soon as the appointment is confirmed.\x02Do I need to " +
	"pay before scheduling an appointment?\x02Yes, you must submit payment in" +
	" order to secure appointment contract. Your payment will be held in escr" +
	"ow until the visit is finalized. Once you submit fees, we will contact t" +
	"he physician and give him or her your medical information. The doctor wi" +
	"ll then confirm appointment, and an email or text will be sent to you, a" +
	"long with the physicians contact information. Fees are structured in amo" +
	"unt of bitcoin (BTC) per unit(U) time (BTC/U). Every unit (U) is equival" +
	"ent to 15 min, time spent in visit will be pre-determined, and visits go" +
	"ing longer that what was agreed upon will not cost extra. All new consul" +
	"ts must be a minimum of 2 units, and repeat visits can be a minimum of 1" +
	" unit.\x02When will I be charged?\x02Bitcoin must be paid in full upon d" +
	"eployment or acceptance of contract.\x02Can I pay with any currency?\x02" +
	"No.\x04\x00\x01 |\x02You can bypass their firewall using tunnel software" +
	" such as a VPN, or Tor software. See the following for more information:" +
	"\x02Olmax Medical | Help\x02How can we help?\x02Suggested Topics\x02Shou" +
	"ld I clear my schedule if I have not heard back from the doctor?\x02How " +
	"do I edit or remove a payment method?\x02What is Bitcoin?\x02How do I us" +
	"e Bitcoin to pay?\x02How can I add another appointment or business addre" +
	"ss to my receipt?\x02How do I verify my phone number?\x02Why didn't I ge" +
	"t my email notification?\x02What is a Verified Medical License?\x02Price" +
	"s & Fees\x02How is the price determined for my appointment?\x02Contactin" +
	"g A Physician\x02What does each appointment status mean?\x02How do I mak" +
	"e an appointment on Olmax?\x02-View all\x04\x00\x01 \x1e\x02All payments" +
	" will be done via\x04\x00\x01 \x11\x02What is Bitcoin?\x04\x00\x01 {\x02" +
	"You can bypass their firewall using tunnel software such as a VPN or Tor" +
	" software. See the following for more information:\x02Prices and fees ar" +
	"e for the most part determined by doctors and patients.\x02Prices are se" +
	"t by who deploys the contract (doctor or patient). Fees are structured i" +
	"n a amount of bitcoin (BTC) per unit. In which a unit of time equals 15 " +
	"mins. All new consults must be a minimum of 2 units, and repeat visits c" +
	"an be 1 unit.\x02No\x02Olmax Medical | Become A Provider\x02Specialty" +
	"\x02Become A Provider\x02Find out what you could earn\x02Get Started\x02" +
	"Why become a provider on Olmax?\x02No matter what your specialty, Olmax " +
	"makes it simple and secure to reach millions of patients looking for doc" +
	"tors with unique skills and specialties, just like yours.\x02You're in c" +
	"ontrol\x02With Olmax, you're in full control of your availability, price" +
	"s, medical management, and how you interact with patients. You can set a" +
	"ppointment times and handle the process however you like.\x02We're there" +
	" at every step\x02Olmax offers tools, service tips, 24/7 support, and an" +
	" on-line community of experienced physicians for questions and sharing i" +
	"deas for success.\x02How to become an Olmax Provider\x02Create your prof" +
	"ile\x02It's free and easy to create a profile on Olmax. Describe your re" +
	"sume, how many patients you can accomodate, set your own times, and add " +
	"photos and details about yourself.\x02Welcome patients\x02Communicate wi" +
	"th patients via 3rd party applications, or personal telephone.\x02Get Pa" +
	"id\x02Olmax's secure payment system means you will never see a patient w" +
	"ithout compensation, or have to deal with money directly. Patienst are c" +
	"harged before appointments, and you are paid after the visit is complete" +
	"d. We embrace the future, therefore payments will be via Bitcoin only." +
	"\x02Safety on Olmax\x02Olmax is built on trust\x02All Olmax physicians m" +
	"ust: submit a profile photo, medical diplomas, residency certification o" +
	"r equivalent, verify their phone, email, government ID, and background c" +
	"hecks. Patients and physicians can each publish reviews after visit conc" +
	"lusions keeping everyone accountable and respectful.\x02Start seeing pat" +
	"ients\x02Profile information such as government ID, diplomas, phone numb" +
	"ers, and emails will will be verified before being posted on Olmax Medic" +
	"al website.\x02Once you have submitted a phone number, you can either re" +
	"ceive a text message or call with a confirmation number.\x02Why did I no" +
	"t get a notification email?\x04\x00\x01 )\x02Please refer to the followi" +
	"ng help page:\x02No selection for question %[1]d\x02Invalid selection fo" +
	"r question %[1]d\x02Full name required\x02Full name must be at least 2 c" +
	"haracters\x02Olmax Medical | Welcome\x02Country\x02Find a Doctor\x02Appo" +
	"intment Dates:\x02From:\x02To:\x02Appointment Times\x02Start Time:\x02En" +
	"d Time:\x02Search\x02Who We Are\x02Olmax Medical is a world wide network" +
	" of physicians and patients that enables them to communicate, meet virtu" +
	"ally, and negotiate payment on a peer to peer basis, without the interfe" +
	"rence of insurance giants. We provide a platform where the economics of " +
	"<i>laissez-fairedes</i> (free-trade) will allow both physicians and pati" +
	"ents to negotiate fee for service. Our website provide a platform where " +
	"both patients and doctors form around the world can deploy customized co" +
	"ntracts describing, in detail, the terms of health care. The cost, time," +
	" and duration of virtual clinic visits will be pre-determined on contrac" +
	"ts posted on our website. The contracts are written by either doctor or " +
	"patient. Contracts can be created, bought, and sold by anyone, because w" +
	"e believe health care should be available to everyone. It will be our wo" +
	"rk to investigate and verify physician status. Once doctors are verified" +
	", patients will have the opportunity to rate physician performance and b" +
	"edside manners.\x02Second Opinions\x02Since the time of Hippocrates, pat" +
	"ients and doctors were limited to serving and receiving care from physic" +
	"ian in their more local community. With our platform patients will not b" +
	"e tied to HMOs or managed health care. In other words, insurance compani" +
	"es or government decisions will no longer chain patients to the type and" +
	" quality of health care they receive. Doctors with extremely rare specia" +
	"lties will be able to serve communities thousands of miles away from the" +
	"m, and from the comfort of their home if they so desire\x02Anonymity\x02" +
	"Patients will be encouraged to use anonymous names. Medical records are " +
	"kept between patients and physicians, they are not stored on our servers" +
	".\x02Access to Physicians from around the world\x02Physicians from aroun" +
	"d the world will be able to join our network, see patients from anywhere" +
	" at anytime.\x02Payment\x02Payments will be made with Bitcoin. Minimal f" +
	"ees will be charged by our website for holding the cryptocurrency until " +
	"clinical visits are complete.\x02See More\x02What are patients saying ab" +
	"out our doctors from\x02Olmax Medical | Login\x02Welcome back!\x02Email:" +
	"\x02Password:\x02Forgot your password?\x02Login\x02Olmax Medical | Messa" +
	"ges\x02You currently have no messages.\x02Previous messages: Click here" +
	"\x02Enter Email\x02We will send a reset code to the email provided\x02Re" +
	"set\x02Olmax Medical | Sign Up\x02Sign Up for free\x02First Name:\x02Ent" +
	"er your first name\x02Enter your last name\x02Last Name:\x02Enter a vali" +
	"d email\x02Enter password (8+ chars)\x02Sign Up\x02Olmax Medical | Walle" +
	"t\x02Wallet\x020 BTC\x02NO FUNDS CURRENTLY HELD IN ESCROW\x02Deposit Fun" +
	"ds\x02Send only Bitcoin (BTC) to this address\x02Sending any other digit" +
	"al asset, including Bitcoin Cash (BCH), will result in permanent loss."

	// Total table size 13636 bytes (13KiB); checksum: 988C101A
